---
- hosts: localhost

  tasks:
    - name: Create project directory
      file: path=/tmp/{{ PROJECT }}/{{ DOMAIN }} state=directory
      tags: docker-swarm-deploy

    - name: Copy Docker Stack File
      copy:
        src: ./compose/docker-compose.yml
        dest: /tmp/{{ PROJECT }}/{{ DOMAIN }}/docker-compose.yml
        mode: u=rw,g=r,o=r
      tags: docker-swarm-deploy

    - name: Deploy Docker Stack
      shell: >
        docker stack deploy -c /tmp/{{ PROJECT }}/{{ DOMAIN }}/docker-compose.yml {{ STACK }} --with-registry-auth
      tags: docker-swarm-deploy
